//Login constants
export const AUTHENTICATE_BEGIN = "AUTHENTICATE_BEGIN";
export const AUTHENTICATE_SUCCESSFULL = "AUTHENTICATE_SUCCESSFULL";
export const AUTHENTICATE_FAILURE = "AUTHENTICATE_FAILURE";
